module.exports = {
  RackPercent:2,
  RoomExpireHours:1,
  RoomExpireHoursCheckCronRepeatTime : 60000,

  waitAfterRoundComplete: 2000,
  waitAfterGameReset:1000,
  waitBeforeGameReset:4000,
  Regular:20000,
  Fast:10000,
  waitBeforeGameStart: 10, //second
  waitBeforGameRestart : 10,


  // Setting Default
  defualtPrcticesChips : 500000, 
  turnTime : 30,
  extraTime : 30,
  playerDropPoint : 80, // Player Drop Point When Drop
  playerDropedRoundCount : 3, // When Player defult 3 turn default then drop player


  // Player Drop Setting
  playerFirstDrop  : 20,
  playerSecondDrop : 40,
  playerThirdDrop  : 80,

  // Points Game
  pointsValue : 20, //  

  // Pool Game 
  gameOverPoint1 : 101,
  setPointValue1 : 20,
  gameOverPoint2 : 201,
  setPointValue2 : 25,

  // Deals Game
  defaultTotalPoints : 160,

  // Dubai Slot 

  jackpot : 0,
  // rooms : 0,

  _jackpot : {},
  _rooms : {
    american: [],
    animal: [],
    fruits: [],
    superhero: [],
    chinese: [],
    christmas: [],
    legacyOfEgypt: [],
    777: [],
    cricket: [],
    dragon: [],
    bookOfRaDeluxe: [],
    fish: [],
    magic: [],
    poker: [],
    candy: [],
    circus: [],
    coins: [],
    construction: [],
    gemstones: [],
    location: [],
    pirates: [],
    soccer: [],
    cherry: [],
    parrot: [],
    royal: [],
    africanKing: [],
    stickyBugs: [],
    diamond: [],
    lobsterParty: [],
    whiteBuffalo: [],
    realRider: [],
    rubberDuck: [],
    goldRush: [],
    bananas: [],
    happyHalloween: [],
    luckyBowl: [],
    richLife: [],
    richesOfEast: [],
    thunderStrike: [],
    vegasVacation: [],
    mountain: [],
    wildCard: [],
    fruitDies: [],
    pokerDies: [],
    casinoPoker: [],
    galaxySlot: [],
    wildFish: [],
    pokerAnimals: [],
    crystalClash: [],
    crushThatBug: [],
    reelKing: [],
    knightDies: [],
    egyptSlots: [],
    wildBird: [],
    fruitBurst: [],
    fishingClash: [],
    wildFox: [],
    cosmic: [],
    mars: [],
    earth: [],
    madagascar: [],
    chinaTown: [],
    portal: [],
    aztecSecret: [],
    arabian: [],
    ghost: [],
    natural: [],
    glodenAge: [],
    pokerHands: [],
    avatar: [],
    infinity: [],
    concert: [],
    heritage: [],
    eyeOfDubai: [],
    heros: [],
    caesars: [],
    lollipop: [],
    candies: [],
    treasure: [],
    ancient: [],
    royalCircus: [],
    candyPop: [],
    stars: [],
    rome: [],
    disney: [],
    wooden: [],
    soldier: [],
    abstract: [],
    burn: [],
    ocean: [],
    scaryJoker: [],
    chineselantern: [],
    art: [],
    halloween: [],
    chakra: [],
    kingSoloman: [],
    kungPanda: [],
    fortune: [],
    wildGems: [],
    ethiopianGems: []
  },

}
